### ISSUE TITLE
Hi! Thanks for sharing

### ISSUE THREAD

**Issue by uNbAs** [dirtyharry123/mca#1]
Thanks for sharing the work!

I was trying to make reversing the MCA to make updates, now I compiled curl, oscam.

When I do a make, either generates flawless filesystem with full_sd.img but when I put the SD in the MCA seems to be installed fine, provided it stays in starting system.

The code that is shared today?

Attached is a log of the compilation:
root@WaRMaChiNe:/home/unbas/Programacion/mca# make clean
rm -rf KERNEL/zImage_packing
rm -rf SD_CONTENT.fat
rm -rf SD_CONTENT_1G.fat
root@WaRMaChiNe:/home/unbas/Programacion/mca# make distclean
rm -rf KERNEL/zImage_packing
rm -rf SD_CONTENT.fat
rm -rf SD_CONTENT_1G.fat
rm -rf distribution/full_sd_image.img
rm -rf distribution/full_sd_image_1G.img
rm -rf distribution/SD_CONTENT/*
root@WaRMaChiNe:/home/unbas/Programacion/mca# make
/usr/sbin/mkfs.jffs2 -r ROOTFS -o distribution/SD_CONTENT/rootfs.jffs2 -e 128 -l -n -q -p
tools/mca_tool.pl -r distribution/SD_CONTENT/rootfs.jffs2
Original CRC32 = FFFFFFFF
Calculated CRC32 = DB21F0DA
CRC replaced
make -C INITRAMFS/initramfs/../
make[1]: se ingresa al directorio «/home/unbas/Programacion/mca/INITRAMFS»
make[1]: No se hace nada para «all».
make[1]: se sale del directorio «/home/unbas/Programacion/mca/INITRAMFS»
cp CONFIG/mcaboot.ini INITRAMFS/initramfs/mca_default.ini
cd KERNEL/ && PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/unbas/Programacion/mca/tools:/home/unbas/Programacion/mca/tools/ /home/unbas/Programacion/mca/tools/repack-zImage.sh -p
Generating initramfs
9260 bloques
Creating gzip compressed initramfs
Padding './zImage_packing/initramfs.cpio.gz' to 1998500 bytes (+16894)
Assembling piggy
Creating piggy.gz
Padding './zImage_packing/piggy.gz' to 3855272 bytes (+16305)
Assembling zImage
Successfully created './zImage_packing/zImage'
Generated file: './zImage_packing/zImage.tar'
dd if=/dev/zero of=distribution/SD_CONTENT/mca_card.bin bs=1024 count=640
640+0 registros leídos
640+0 registros escritos
655360 bytes (655 kB) copiados, 0,00346387 s, 189 MB/s
dd if=BLOBS/apex_flash.bin of=distribution/SD_CONTENT/mca_card.bin bs=512 conv=notrunc
133+1 registros leídos
133+1 registros escritos
68304 bytes (68 kB) copiados, 0,0141116 s, 4,8 MB/s
dd if=KERNEL/zImage_packing/zImage of=distribution/SD_CONTENT/mca_card.bin bs=1024 seek=640 conv=notrunc
4096+0 registros leídos
4096+0 registros escritos
4194304 bytes (4,2 MB) copiados, 0,0222665 s, 188 MB/s
cp CONFIG/mcaboot.ini distribution/SD_CONTENT/mcaboot.ini
cp CONFIG/mca.ini distribution/SD_CONTENT/mca.ini
dd if=/dev/zero of=SD_CONTENT.fat bs=1024 count=1879716
1879716+0 registros leídos
1879716+0 registros escritos
1924829184 bytes (1,9 GB) copiados, 42,6295 s, 45,2 MB/s
/sbin/mkfs.vfat -F 16 -n mca_ng SD_CONTENT.fat
mkfs.fat 3.0.26 (2014-03-07)
mkfs.fat: warning - lowercase labels might not work properly with DOS or Windows
mkdir SD_MNT
sudo mount -o loop SD_CONTENT.fat SD_MNT
sudo cp -r distribution/SD_CONTENT/\* SD_MNT/
sudo umount SD_MNT
rm -rf SD_MNT
dd if=/dev/zero of=distribution/full_sd_image.img bs=512 count=126852
126852+0 registros leídos
126852+0 registros escritos
64948224 bytes (65 MB) copiados, 0,552782 s, 117 MB/s
dd if=BLOBS/SD_MBR.bin of=distribution/full_sd_image.img bs=512 conv=notrunc
1+0 registros leídos
1+0 registros escritos
512 bytes (512 B) copiados, 0,00695987 s, 73,6 kB/s
dd if=BLOBS/apex_sd.bin of=distribution/full_sd_image.img bs=512 seek=62 conv=notrunc
129+1 registros leídos
129+1 registros escritos
66064 bytes (66 kB) copiados, 0,0417116 s, 1,6 MB/s
dd if=SD_CONTENT.fat of=distribution/full_sd_image.img oflag=append conv=notrunc
3759432+0 registros leídos
3759432+0 registros escritos
1924829184 bytes (1,9 GB) copiados, 86,8751 s, 22,2 MB/s

The changes are made or ROOTFS.min rootfs?

**Comment by uNbAs** [comment]
Today I tried to modify the Makefile to create a full_sd_1G but I have the same problem "Initializing sistem"

I tried to download the source and build the Full_SD_1G without any changes to the file system but also feel the same

**Comment by dirtyharry123** [comment]
Could you please post the output of:
**ls -lha INITRAMFS/initramfs/**
and:
**ls -lha INITRAMFS/initramfs/dev/**

**Comment by uNbAs** [comment]
You think is permission problem? Thanks for your reply!

unbas@WaRMaChiNe:~/Programacion/mca$ ls -lha INITRAMFS/initramfs/
total 80K
drwx------ 16 unbas unbas 4,0K ene  1  1970 .
drwx------  3 unbas unbas 4,0K nov 11 21:52 ..
drwx------  2 unbas unbas 4,0K ene  1  1970 bin
drwx------  6 unbas unbas 4,0K ene  1  1970 dev
drwx------  4 unbas unbas 4,0K ene  1  1970 etc
drwx------  2 unbas unbas 4,0K ene  1  1970 include
-rwxr-xr-x  1 unbas unbas 8,1K ene  1  1970 init
drwx------  3 unbas unbas 4,0K ene  1  1970 lib
lrwxrwxrwx  1 unbas unbas   11 ene  1  1970 linuxrc -> bin/busybox
drwxrwxr-x  2 unbas unbas 4,0K ene  1  1970 man
-rwxr-xr-x  1 unbas unbas 1,4K nov 22 08:43 mca_default.ini
drwxrwxr-x  2 unbas unbas 4,0K ene  1  1970 mnt
drwxrwxr-x  2 unbas unbas 4,0K ene  1  1970 newroot
drwxrwxr-x  2 unbas unbas 4,0K ene  1  1970 proc
drwx------  2 unbas unbas 4,0K ene  1  1970 sbin
drwxrwxr-x  2 unbas unbas 4,0K ene  1  1970 sys
drwxrwxr-x  2 unbas unbas 4,0K ene  1  1970 tmp
drwx------  7 unbas unbas 4,0K ene  1  1970 usr
drwxrwxr-x  2 unbas unbas 4,0K ene  1  1970 var

##############################################################################
##############################################################################

unbas@WaRMaChiNe:~/Programacion/mca$  ls -lha INITRAMFS/initramfs/dev/
total 24K
drwx------  6 unbas unbas 4,0K ene  1  1970 .
drwx------ 16 unbas unbas 4,0K ene  1  1970 ..
crw-------  1 root  root  5, 1 ene  1  1970 console
drwxrwxr-x  2 unbas unbas 4,0K ene  1  1970 input
lrwxrwxrwx  1 unbas unbas   12 ene  1  1970 log -> /var/tmp/log
lrwxrwxrwx  1 unbas unbas   12 ene  1  1970 mtab -> /proc/mounts
drwxrwxr-x  2 unbas unbas 4,0K ene  1  1970 net
crw-rw-rw-  1 root  root  1, 3 ene  1  1970 null
drwxrwxr-x  2 unbas unbas 4,0K ene  1  1970 pts
drwxrwxr-x  2 unbas unbas 4,0K ene  1  1970 shm

**Comment by uNbAs** [comment]
I changed the owner recursively to be root, but the install is the same, stays in initiating system and never ends.
The method I've used is to download the compressed source, svn co unfortunately does not work, but because of my system I have a problem with dependencies svn

root@WaRMaChiNe:/home/unbas/Programacion/mca-master# ls -lha INITRAMFS/initramfs/
total 80K
drwx------ 16 root root 4,0K ene  1  1970 .
drwx------  3 root root 4,0K nov 23 12:01 ..
drwx------  2 root root 4,0K ene  1  1970 bin
drwx------  6 root root 4,0K ene  1  1970 dev
drwx------  4 root root 4,0K ene  1  1970 etc
drwx------  2 root root 4,0K ene  1  1970 include
-rwxr-xr-x  1 root root 8,1K ene  1  1970 init
drwx------  3 root root 4,0K ene  1  1970 lib
lrwxrwxrwx  1 root root   11 ene  1  1970 linuxrc -> bin/busybox
drwxr-xr-x  2 root root 4,0K ene  1  1970 man
-rwxr-xr-x  1 root root 1,4K ene  1  1970 mca_default.ini
drwxr-xr-x  2 root root 4,0K ene  1  1970 mnt
drwxr-xr-x  2 root root 4,0K ene  1  1970 newroot
drwxr-xr-x  2 root root 4,0K ene  1  1970 proc
drwx------  2 root root 4,0K ene  1  1970 sbin
drwxr-xr-x  2 root root 4,0K ene  1  1970 sys
drwxr-xr-x  2 root root 4,0K ene  1  1970 tmp
drwx------  7 root root 4,0K ene  1  1970 usr
drwxr-xr-x  2 root root 4,0K ene  1  1970 var
root@WaRMaChiNe:/home/unbas/Programacion/mca-master# 

root@WaRMaChiNe:/home/unbas/Programacion/mca-master#  ls -lha INITRAMFS/initramfs/dev/
total 24K
drwx------  6 root root 4,0K ene  1  1970 .
drwx------ 16 root root 4,0K ene  1  1970 ..
crw-------  1 root root 5, 1 ene  1  1970 console
drwxr-xr-x  2 root root 4,0K ene  1  1970 input
lrwxrwxrwx  1 root root   12 ene  1  1970 log -> /var/tmp/log
lrwxrwxrwx  1 root root   12 ene  1  1970 mtab -> /proc/mounts
drwxr-xr-x  2 root root 4,0K ene  1  1970 net
crw-rw-rw-  1 root root 1, 3 ene  1  1970 null
drwxr-xr-x  2 root root 4,0K ene  1  1970 pts
drwxr-xr-x  2 root root 4,0K ene  1  1970 shm
root@WaRMaChiNe:/home/unbas/Programacion/mca-master#

**Comment by dirtyharry123** [comment]
Fixed in 91d4842ea398f8148881d3ff259e0dc31c512897
